name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  win:
    runs-on: windows-latest
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4
      - name: Install Depot Tools
        uses: newkdev/setup-depot-tools@v1.0.1
      - run: |
          mkdir angle
          cd angle
          fetch --no-history angle
      - run: gn gen out/Release
        working-directory: angle
      - run: autoninja -C out/Release
        working-directory: angle
      
